//go:build e2e

package inputpipeline

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/Dyu-36/gotack/internal/crushapi"
)

// Paired benchmark driver. This is a Go benchmark, not a test, so the E2E
// gate lane never executes it; scripts/bench-input-pipeline.ps1 invokes it
// with explicit artifacts and a schedule generated by the same statistics
// core that later aggregates the records. Every record carries measured
// telemetry only: absent marks stay absent, failures are outcomes rather
// than synthesized numbers, and no prompt, session ID, or request body is
// ever written to the record stream.
func BenchmarkPairedTurns(b *testing.B) {
	recordPath := os.Getenv("TACK_BENCH_RECORD")
	scheduleRaw := os.Getenv("TACK_BENCH_SCHEDULE")
	if !filepath.IsAbs(recordPath) || scheduleRaw == "" {
		b.Fatal("benchmark_artifacts_required")
	}
	var schedule []struct {
		Pair  int      `json:"pair"`
		Order []string `json:"order"`
	}
	if json.Unmarshal([]byte(scheduleRaw), &schedule) != nil || len(schedule) == 0 {
		b.Fatal("benchmark_schedule_invalid")
	}
	var key [16]byte
	if _, err := rand.Read(key[:]); err != nil {
		b.Fatal("benchmark_key_unavailable")
	}
	cacheKey := "bench-" + hex.EncodeToString(key[:])

	file, err := os.OpenFile(recordPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
	if err != nil {
		b.Fatal("benchmark_record_open_failed")
	}
	encoder := json.NewEncoder(file)
	b.Cleanup(func() {
		if closeErr := file.Close(); closeErr != nil {
			b.Error("benchmark_record_close_failed")
		}
	})

	provider := newFakeProvider()
	b.Cleanup(provider.close)

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		for _, entry := range schedule {
			for _, arm := range entry.Order {
				record := runBenchArm(b, provider, entry.Pair, arm, cacheKey)
				if encodeErr := encoder.Encode(record); encodeErr != nil {
					b.Fatal("benchmark_record_write_failed")
				}
			}
		}
	}
}

func runBenchArm(b *testing.B, p *fakeProvider, pair int, arm, cacheKey string) map[string]any {
	var modelOptions map[string]any
	switch arm {
	case "A":
	case "B":
		// The engine's provider-options layers merge as flat option maps;
		// provider-name wrapping would be an inert nested key.
		modelOptions = map[string]any{"prompt_cache_key": cacheKey}
	default:
		b.Fatal("benchmark_arm_invalid")
	}
	root := b.TempDir()
	h := startEngine(b, root, p, false, modelOptions)
	session := freshSession(b, h)
	run := newID(b)
	p.arm(run, modeText)
	if err := h.client.SendPromptWithAttachments(h.ctx, h.workspace, session, "Run the synthetic fixture.", run, nil); err != nil {
		b.Fatal("prompt_submit_failed")
	}
	var matching []byte
	terminal, err := waitTerminal(h.ctx, func(ctx context.Context) ([]byte, error) {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case event, ok := <-h.events:
			if !ok {
				return nil, errors.New("stream_closed")
			}
			matching = event.Payload
			return event.Payload, nil
		}
	}, run, session)
	if err != nil {
		b.Fatal("matching_terminal_missing")
	}
	counts := p.counts(run)
	h.stop()
	if err := checkCapture(counts, 1); err != nil {
		b.Fatal("provider_capture_invalid")
	}
	switch arm {
	case "A":
		if counts.CacheKeyRequest != 0 {
			b.Fatal("benchmark_control_contaminated")
		}
	case "B":
		if counts.CacheKeyRequest != counts.Requests {
			b.Fatal("benchmark_treatment_ineffective")
		}
	}
	record, err := benchRecord(pair, arm, terminal, matching, counts)
	if err != nil {
		b.Fatal(err.Error())
	}
	return record
}

type benchTerminal struct {
	terminalPayload
	Telemetry *crushapi.RunTelemetry `json:"telemetry,omitempty"`
}

// benchRecord projects the engine terminal event into the statistics-core
// record schema. local preparation sums only spans the engine actually
// closed; spans that require engine hooks that did not run stay null rather
// than becoming zero.
func benchRecord(pair int, arm string, terminal terminalPayload, raw []byte, counts captureCounts) (map[string]any, error) {
	var payload benchTerminal
	if json.Unmarshal(raw, &payload) != nil {
		return nil, errors.New("terminal_schema_invalid")
	}
	if payload.Telemetry == nil {
		return nil, errors.New("benchmark_telemetry_missing")
	}
	telemetry := payload.Telemetry
	outcome := "success"
	if terminal.Error != "" || terminal.Cancelled || terminal.Text != fixtureAnswer {
		outcome = "error"
	}
	spans := telemetry.SpansMicros
	localPreparation := map[string]int64{}
	for _, name := range []string{"ready_wait", "mcp_wait", "model_refresh", "skill_scan", "tool_build", "history_load", "prompt_prepare"} {
		if value, ok := spans[name]; ok {
			localPreparation[name] = value
		}
	}
	var localTotal *int64
	if len(localPreparation) > 0 {
		sum := int64(0)
		for _, value := range localPreparation {
			sum += value
		}
		localTotal = &sum
	}
	spanOrNull := func(name string) any {
		if value, ok := spans[name]; ok {
			return value
		}
		return nil
	}
	cacheStatus := telemetry.CacheStatus
	if cacheStatus == "" {
		cacheStatus = "unreported"
	}
	return map[string]any{
		"pair":         pair,
		"arm":          arm,
		"outcome":      outcome,
		"requests":     counts.Requests,
		"retries":      counts.Retries,
		"cache_status": cacheStatus,
		"metrics": map[string]any{
			"local_preparation_us": localTotal,
			"http_ttfb_us":         spanOrNull("request_write_to_first_byte"),
			"first_reasoning_us":   spanOrNull("first_reasoning"),
			"first_tool_us":        spanOrNull("first_tool"),
			"first_text_us":        spanOrNull("first_text"),
			"total_us":             telemetry.TotalMicros,
			"summarize_us":         spanOrNull("summarize"),
		},
	}, nil
}
